// File generated from our OpenAPI spec by Stainless.

package com.withorb.api.models

import com.withorb.api.core.JsonValue
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

class EditCustomerModelTest {

    @Test
    fun createEditCustomerModel() {
        val editCustomerModel =
            EditCustomerModel.builder()
                .accountingSyncConfiguration(
                    NewAccountingSyncConfigurationModel.builder()
                        .addAccountingProvider(
                            NewAccountingSyncConfigurationModel.AccountingProvider.builder()
                                .externalProviderId("external_provider_id")
                                .providerType("provider_type")
                                .build()
                        )
                        .excluded(true)
                        .build()
                )
                .addAdditionalEmail("string")
                .autoCollection(true)
                .billingAddress(
                    AddressInputModel.builder()
                        .city("city")
                        .country("country")
                        .line1("line1")
                        .line2("line2")
                        .postalCode("postal_code")
                        .state("state")
                        .build()
                )
                .currency("currency")
                .email("dev@stainless.com")
                .emailDelivery(true)
                .externalCustomerId("external_customer_id")
                .hierarchy(
                    CustomerHierarchyConfigModel.builder()
                        .addChildCustomerId("string")
                        .parentCustomerId("parent_customer_id")
                        .build()
                )
                .metadata(
                    EditCustomerModel.Metadata.builder()
                        .putAdditionalProperty("foo", JsonValue.from("string"))
                        .build()
                )
                .name("name")
                .paymentProvider(EditCustomerModel.PaymentProvider.QUICKBOOKS)
                .paymentProviderId("payment_provider_id")
                .reportingConfiguration(
                    NewReportingConfigurationModel.builder().exempt(true).build()
                )
                .shippingAddress(
                    AddressInputModel.builder()
                        .city("city")
                        .country("country")
                        .line1("line1")
                        .line2("line2")
                        .postalCode("postal_code")
                        .state("state")
                        .build()
                )
                .taxConfiguration(
                    NewTaxConfigurationModel.NewAvalaraTaxConfiguration.builder()
                        .taxExempt(true)
                        .taxProvider(
                            NewTaxConfigurationModel.NewAvalaraTaxConfiguration.TaxProvider.AVALARA
                        )
                        .taxExemptionCode("tax_exemption_code")
                        .build()
                )
                .taxId(
                    CustomerTaxIdModel.builder()
                        .country(CustomerTaxIdModel.Country.AD)
                        .type(CustomerTaxIdModel.Type.AD_NRT)
                        .value("value")
                        .build()
                )
                .build()
        assertThat(editCustomerModel).isNotNull
        assertThat(editCustomerModel.accountingSyncConfiguration())
            .isEqualTo(
                NewAccountingSyncConfigurationModel.builder()
                    .addAccountingProvider(
                        NewAccountingSyncConfigurationModel.AccountingProvider.builder()
                            .externalProviderId("external_provider_id")
                            .providerType("provider_type")
                            .build()
                    )
                    .excluded(true)
                    .build()
            )
        assertThat(editCustomerModel.additionalEmails()).containsExactly("string")
        assertThat(editCustomerModel.autoCollection()).isEqualTo(true)
        assertThat(editCustomerModel.billingAddress())
            .isEqualTo(
                AddressInputModel.builder()
                    .city("city")
                    .country("country")
                    .line1("line1")
                    .line2("line2")
                    .postalCode("postal_code")
                    .state("state")
                    .build()
            )
        assertThat(editCustomerModel.currency()).isEqualTo("currency")
        assertThat(editCustomerModel.email()).isEqualTo("dev@stainless.com")
        assertThat(editCustomerModel.emailDelivery()).isEqualTo(true)
        assertThat(editCustomerModel.externalCustomerId()).isEqualTo("external_customer_id")
        assertThat(editCustomerModel.hierarchy())
            .isEqualTo(
                CustomerHierarchyConfigModel.builder()
                    .addChildCustomerId("string")
                    .parentCustomerId("parent_customer_id")
                    .build()
            )
        assertThat(editCustomerModel.metadata())
            .isEqualTo(
                EditCustomerModel.Metadata.builder()
                    .putAdditionalProperty("foo", JsonValue.from("string"))
                    .build()
            )
        assertThat(editCustomerModel.name()).isEqualTo("name")
        assertThat(editCustomerModel.paymentProvider())
            .isEqualTo(EditCustomerModel.PaymentProvider.QUICKBOOKS)
        assertThat(editCustomerModel.paymentProviderId()).isEqualTo("payment_provider_id")
        assertThat(editCustomerModel.reportingConfiguration())
            .isEqualTo(NewReportingConfigurationModel.builder().exempt(true).build())
        assertThat(editCustomerModel.shippingAddress())
            .isEqualTo(
                AddressInputModel.builder()
                    .city("city")
                    .country("country")
                    .line1("line1")
                    .line2("line2")
                    .postalCode("postal_code")
                    .state("state")
                    .build()
            )
        assertThat(editCustomerModel.taxConfiguration())
            .isEqualTo(
                NewTaxConfigurationModel.ofAvalaraTaxConfiguration(
                    NewTaxConfigurationModel.NewAvalaraTaxConfiguration.builder()
                        .taxExempt(true)
                        .taxProvider(
                            NewTaxConfigurationModel.NewAvalaraTaxConfiguration.TaxProvider.AVALARA
                        )
                        .taxExemptionCode("tax_exemption_code")
                        .build()
                )
            )
        assertThat(editCustomerModel.taxId())
            .isEqualTo(
                CustomerTaxIdModel.builder()
                    .country(CustomerTaxIdModel.Country.AD)
                    .type(CustomerTaxIdModel.Type.AD_NRT)
                    .value("value")
                    .build()
            )
    }
}
